[theme]
# A soothing, smooth pastel theme based on the provided palette
primaryColor = "#A58A89"
backgroundColor = "#DCCBC7"
secondaryBackgroundColor = "#CBB4B0"
textColor = "#3d3435"
font = "sans serif"
